<a href="https://colab.research.google.com/github/Looma1116/Kaggle-Study_Seungjoon_Lee/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
 import torch
 import torch.optim as optim


 x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[4,2]]
 y_data = [[0],[0],[0],[1],[1],[1]]

 x_train = torch.FloatTensor(x_data)
 y_train = torch.FloatTensor(y_data)

 print(x_train,x_train.shape)
 print(y_train,y_train.shape)
  

tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [4., 2.]]) torch.Size([6, 2])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]]) torch.Size([6, 1])


In [4]:
W = torch.zeros((2,1),requires_grad=True)
b = torch.zeros(1,requires_grad=True)

optimizer = optim.SGD([W,b],lr = 1)

nb_epochs = 10001
for epoch in range(nb_epochs):
  hypothesis = torch.sigmoid(x_train@W+b)
  cost = -(y_train*torch.log(hypothesis)+(1-y_train)*torch.log(1-hypothesis)).mean()

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 500 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch,nb_epochs,cost.item()))

Epoch    0/10001 Cost: 0.693147
Epoch  500/10001 Cost: 0.054055
Epoch 1000/10001 Cost: 0.029379
Epoch 1500/10001 Cost: 0.020221
Epoch 2000/10001 Cost: 0.015434
Epoch 2500/10001 Cost: 0.012490
Epoch 3000/10001 Cost: 0.010494
Epoch 3500/10001 Cost: 0.009052
Epoch 4000/10001 Cost: 0.007960
Epoch 4500/10001 Cost: 0.007105
Epoch 5000/10001 Cost: 0.006417
Epoch 5500/10001 Cost: 0.005851
Epoch 6000/10001 Cost: 0.005377
Epoch 6500/10001 Cost: 0.004975
Epoch 7000/10001 Cost: 0.004629
Epoch 7500/10001 Cost: 0.004328
Epoch 8000/10001 Cost: 0.004065
Epoch 8500/10001 Cost: 0.003831
Epoch 9000/10001 Cost: 0.003624
Epoch 9500/10001 Cost: 0.003437
Epoch 10000/10001 Cost: 0.003269


In [5]:
print(hypothesis)

prediction = hypothesis >= torch.FloatTensor([0.5])
print('Prediction:')
print(prediction)
print('Label:')
print(y_train>=torch.FloatTensor([0.5]))

tensor([[1.7277e-07],
        [2.4831e-03],
        [8.9284e-03],
        [9.9951e-01],
        [1.0000e+00],
        [9.9235e-01]], grad_fn=<SigmoidBackward>)
Prediction:
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])
Label:
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])


In [15]:
XX = torch.FloatTensor([100,1])  ##100시간 공부하고 수업 1번 참여하면??
hypothesis_test = torch.sigmoid(XX@W+b)
prediction = hypothesis_test >= torch.FloatTensor([0.5])
print(prediction) #시험 통과!

tensor([True])
